name = "ai-publisher"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Variables
[vars]
NODE_ENV = "production"
ENVIRONMENT = "production"

# Production environment
[env.production]
name = "ai-publisher-prod"
vars = { NODE_ENV = "production", ENVIRONMENT = "production" }

# KV Namespaces (will be created automatically)
[[kv_namespaces]]
binding = "CACHE"
id = "placeholder"
preview_id = "placeholder"

# R2 Buckets (will be created automatically)
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "ai-publisher-media"
