name: Deploy AI Publisher to Cloudflare Workers

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run type-check

      - name: Run tests
        run: npm test

  deploy-staging:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: test
    name: Deploy to Staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Cloudflare Workers (Staging)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env staging
          workingDirectory: '.'

  deploy-production:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: test
    name: Deploy to Production
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Cloudflare Workers (Production)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --env production
          workingDirectory: '.'
          secrets: |
            GEMINI_API_KEY
            TWITTER_CLIENT_ID
            TWITTER_CLIENT_SECRET
            FACEBOOK_APP_ID
            FACEBOOK_APP_SECRET
            INSTAGRAM_CLIENT_ID
            INSTAGRAM_CLIENT_SECRET
            LINKEDIN_CLIENT_ID
            LINKEDIN_CLIENT_SECRET
            YOUTUBE_CLIENT_ID
            YOUTUBE_CLIENT_SECRET
            TIKTOK_CLIENT_KEY
            TIKTOK_CLIENT_SECRET
            OPENAI_API_KEY
            SUPABASE_URL
            SUPABASE_ANON_KEY
            SUPABASE_SERVICE_ROLE_KEY

      - name: Create GitHub Release
        if: success()
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          body: |
            🚀 Automated deployment to Cloudflare Workers
            
            **Changes in this release:**
            ${{ github.event.head_commit.message }}
            
            **Deployment Details:**
            - Environment: Production
            - Commit: ${{ github.sha }}
            - Deployed at: ${{ github.event.head_commit.timestamp }}
            
            **Links:**
            - [Live Site](https://ai-publisher.com)
            - [Commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
          draft: false
          prerelease: false

  notify:
    if: always()
    runs-on: ubuntu-latest
    needs: [test, deploy-production]
    name: Notify Deployment Status
    steps:
      - name: Notify Success
        if: needs.deploy-production.result == 'success'
        run: |
          echo "🎉 Deployment successful!"
          echo "Site is live at: https://ai-publisher.com"

      - name: Notify Failure
        if: needs.deploy-production.result == 'failure'
        run: |
          echo "❌ Deployment failed!"
          echo "Please check the logs for more information."
